version: "3.8"
services:
  scheduler:
    build:
      context: ..
      dockerfile: stress/Dockerfile
    command: /opt/stress/stress.exe --listen-prometheus=9090
    init: true
    ports:
      - "5000:5000"
    volumes:
      - "../capnp-secrets:/capnp-secrets"
      - "../_build/default/stress:/opt/stress:ro"
  grafana:
    build: './grafana'
    ports:
      - "3000:3000"
    #volumes:
    #  - "./grafana-config:/var/lib/grafana"
  prometheus:
    image: prom/prometheus
    command: --storage.tsdb.retention.time=30w --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    #ports:
    #  - "9090:9090"
    volumes:
      - "prometheus-data:/prometheus"
      - "./prometheus:/etc/prometheus:ro"
volumes:
  prometheus-data:
